# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login_Form(object):
    def setupUi(self, Login_Form):
        Login_Form.setObjectName("Login_Form")
        Login_Form.resize(1273, 743)
        Login_Form.setAutoFillBackground(False)
        Login_Form.setStyleSheet("")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(Login_Form)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame = QtWidgets.QFrame(Login_Form)
        self.frame.setStyleSheet("#frame{border-image: url(:/Login/2.png);}\n"
"\n"
"\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 150, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(350, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.511, x2:1, y2:0.551, stop:0 rgba(0, 85, 255,250), stop:1 rgba(85, 170, 255,200));\n"
"\n"
"\n"
"border-radius:20px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(20, 120, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem2)
        self.label = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{background-color: rgba(255, 255, 255,0);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 24pt \"等线\";\n"
"\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        spacerItem3 = QtWidgets.QSpacerItem(20, 107, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setStyleSheet("QLabel{background-color: rgba(255, 255, 255,0);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 9pt \"等线\";\n"
"\n"
"}")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem4)
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setStyleSheet("background-color: rgba(85, 170, 255,200);\n"
"border-radius:20px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setStyleSheet("background-color: rgba(255, 255, 255,0);\n"
"border-radius:0px;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.btn_close = QtWidgets.QPushButton(self.frame_6)
        self.btn_close.setMaximumSize(QtCore.QSize(20, 20))
        self.btn_close.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Login/loginClose.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close.setIcon(icon)
        self.btn_close.setIconSize(QtCore.QSize(20, 20))
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_6.addWidget(self.btn_close)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        self.label_3.setStyleSheet("QLabel{background-color: rgba(255, 255, 255,0);\n"
"    color: rgb(20, 20, 20);\n"
"    font: 75 16pt \"等线\";\n"
"\n"
"}")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.verticalLayout_6.setStretch(0, 1)
        self.verticalLayout_6.setStretch(1, 5)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setStyleSheet("background-color: rgba(255, 255, 255,0);\n"
"border-radius:0px;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem8 = QtWidgets.QSpacerItem(35, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.frame_5)
        self.label_4.setStyleSheet("QLabel{background-color: rgba(255, 255, 255,0);\n"
"    color: rgb(20, 20, 20);\n"
"    font: 75 12pt \"等线\";\n"
"\n"
"}")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.lineEdit_account = QtWidgets.QLineEdit(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_account.setFont(font)
        self.lineEdit_account.setStyleSheet("QLineEdit {  \n"
"                background-color: rgba(255, 255, 255, 0);  /* 透明背景 */  \n"
"                border-style: outset;  \n"
"                border-width: 1px;  \n"
"                border-top: none;\n"
"                border-left:none;\n"
"                border-right:none;\n"
"                border-color: rgba(0, 0, 0, 255);  /* 黑色边框 */  \n"
"                border-radius: 0px;  \n"
"                padding: 2px;  \n"
"            }  \n"
"              \n"
"            QLineEdit:hover {  \n"
"                border-color: rgba(0, 140, 255, 255);  /* 鼠标悬停时边框变为蓝色 */  \n"
"            }  \n"
"              \n"
"            QLineEdit:focus {  \n"
"                border-color: rgba(0, 140, 255, 255);  /* 获得焦点时边框变为蓝色 */  \n"
"            }")
        self.lineEdit_account.setInputMask("")
        self.lineEdit_account.setText("")
        self.lineEdit_account.setMaxLength(20)
        self.lineEdit_account.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_account.setObjectName("lineEdit_account")
        self.gridLayout.addWidget(self.lineEdit_account, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        self.label_5.setStyleSheet("QLabel{background-color: rgba(255, 255, 255,0);\n"
"    color: rgb(20, 20, 20);\n"
"    font: 75 12pt \"等线\";\n"
"\n"
"}")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.lineEdit_pwd = QtWidgets.QLineEdit(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_pwd.setFont(font)
        self.lineEdit_pwd.setStyleSheet("QLineEdit {  \n"
"                background-color: rgba(255, 255, 255, 0);  /* 透明背景 */  \n"
"                border-style: outset;  \n"
"                border-width: 1px;  \n"
"                border-top: none;\n"
"                border-left:none;\n"
"                border-right:none;\n"
"                border-color: rgba(0, 0, 0, 255);  /* 黑色边框 */  \n"
"                border-radius: 0px;  \n"
"                padding: 2px;  \n"
"            }  \n"
"              \n"
"            QLineEdit:hover {  \n"
"                border-color: rgba(0, 140, 255, 255);  /* 鼠标悬停时边框变为蓝色 */  \n"
"            }  \n"
"              \n"
"            QLineEdit:focus {  \n"
"                border-color: rgba(0, 140, 255, 255);  /* 获得焦点时边框变为蓝色 */  \n"
"            }")
        self.lineEdit_pwd.setInputMask("")
        self.lineEdit_pwd.setText("")
        self.lineEdit_pwd.setMaxLength(20)
        self.lineEdit_pwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_pwd.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_pwd.setObjectName("lineEdit_pwd")
        self.gridLayout.addWidget(self.lineEdit_pwd, 1, 1, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout)
        spacerItem9 = QtWidgets.QSpacerItem(35, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem9)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3.addWidget(self.frame_5)
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setStyleSheet("background-color: rgba(255, 255, 255,0);\n"
"border-radius:0px;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem10 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem10)
        self.remember_pwd_checkBox = QtWidgets.QCheckBox(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        self.remember_pwd_checkBox.setFont(font)
        self.remember_pwd_checkBox.setObjectName("remember_pwd_checkBox")
        self.horizontalLayout_7.addWidget(self.remember_pwd_checkBox)
        spacerItem11 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem11)
        self.auto_login_checkBox = QtWidgets.QCheckBox(self.frame_4)
        self.auto_login_checkBox.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        self.auto_login_checkBox.setFont(font)
        self.auto_login_checkBox.setObjectName("auto_login_checkBox")
        self.horizontalLayout_7.addWidget(self.auto_login_checkBox)
        spacerItem12 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem12)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_7)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        self.frame_7.setStyleSheet("background-color: rgba(255, 255, 255,0);\n"
"border-radius:0px;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem13 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem13)
        self.Login_btn = QtWidgets.QPushButton(self.frame_7)
        self.Login_btn.setMinimumSize(QtCore.QSize(182, 50))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Login_btn.setFont(font)
        self.Login_btn.setStyleSheet("QPushButton {  \n"
"                background-color: rgb(0,0,0); /* 按钮背景颜色 */  \n"
"                border:none;\n"
"                border-radius: 10px; /* 圆角半径 */  \n"
"                font: bold 14px;  \n"
"                min-width: 10em;  \n"
"                padding: 6px; \n"
" \n"
"    font: 12pt \"等线\";\n"
"    color: rgb(255, 255, 255);\n"
"            }  \n"
"              \n"
"            QPushButton:pressed {  \n"
"                background-color: rgb(100,100,100); /* 按钮按下时的背景颜色 */  \n"
"                border-style: inset;  \n"
"            }")
        self.Login_btn.setObjectName("Login_btn")
        self.horizontalLayout_8.addWidget(self.Login_btn)
        self.btn_clear = QtWidgets.QPushButton(self.frame_7)
        self.btn_clear.setMaximumSize(QtCore.QSize(35, 35))
        self.btn_clear.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Login/clear(1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_clear.setIcon(icon1)
        self.btn_clear.setIconSize(QtCore.QSize(30, 30))
        self.btn_clear.setObjectName("btn_clear")
        self.horizontalLayout_8.addWidget(self.btn_clear)
        spacerItem14 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem14)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.verticalLayout_3.addWidget(self.frame_7)
        self.verticalLayout_3.setStretch(0, 30)
        self.verticalLayout_3.setStretch(1, 30)
        self.verticalLayout_3.setStretch(2, 15)
        self.verticalLayout_3.setStretch(3, 20)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.horizontalLayout.addWidget(self.frame_3)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        spacerItem15 = QtWidgets.QSpacerItem(350, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem15)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem16 = QtWidgets.QSpacerItem(20, 150, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem16)
        self.horizontalLayout_11.addLayout(self.verticalLayout)
        self.horizontalLayout_3.addWidget(self.frame)

        self.retranslateUi(Login_Form)
        QtCore.QMetaObject.connectSlotsByName(Login_Form)

    def retranslateUi(self, Login_Form):
        _translate = QtCore.QCoreApplication.translate
        Login_Form.setWindowTitle(_translate("Login_Form", "用户登录"))
        self.label.setText(_translate("Login_Form", "超高压地面测试流程\n"
"\n"
"综合分析软件"))
        self.label_2.setText(_translate("Login_Form", "WELCOME"))
        self.label_3.setText(_translate("Login_Form", "用户登录"))
        self.label_4.setText(_translate("Login_Form", "  账     号"))
        self.label_5.setText(_translate("Login_Form", "  密     码"))
        self.remember_pwd_checkBox.setText(_translate("Login_Form", "记住密码"))
        self.auto_login_checkBox.setText(_translate("Login_Form", "自动登录"))
        self.Login_btn.setText(_translate("Login_Form", "登     录"))
import image.image_res_rc
